version: 2.1
jobs:
  shapecheck:
    working_directory: ~/oslc-specs
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      - run:
          name: ShapeChecker Gradle build
          command: cd tools/ShapeChecker && ./gradlew --console=plain installDist
          condition: always()
      - run:
          name: Check shapes & vocabs for  primary domains
          command: cd tools/ShapeChecker && ./check-main.sh
  prettier:
    working_directory: ~/oslc-specs
    docker:
      - image: node:lts
    steps:
      - checkout
      - run:
          name: Install prettier
          command: npm install --global prettier
      - run:
          name: Check spec formatting
          command: ./.circleci/prettier-main.sh
workflows:
  spec-check:
    jobs:
      - shapecheck
      - prettier
